# Generated by Django 5.0.4 on 2024-04-26 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_certificado_duracaocert'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificado',
            name='duracaoCert',
            field=models.DurationField(verbose_name='Duração do Curso'),
        ),
    ]
